config/routes.rb
SviHackathon::Application.routes.draw do
  resources :checkins
  match 'checkins/:id/checkout' => 'checkins#checkout'

  root :to => "home#index"

end

app/models/checkin.rb
class Checkin < ActiveRecord::Base
  validates :name,
    :presence => true,
    :length => { :minimum => 2 }

  validates_exclusion_of :name, :in => ["What's your name?"],
    :message => "Looks like you left the default text in place."

  validates_exclusion_of :email, :in => ["What's your email?"],
    :message => "Looks like you left the default text in place."

  validates_exclusion_of :status, :in => ["What are you working on?"],
    :message => "Looks like you left the default text in place."



  validates :email, :presence => true, :length => { :minimum => 2 }
  validates :status, :presence => true, :length => { :minimum => 2 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/checkins_controller.rb
class CheckinsController < ApplicationController
  # GET /checkins
  # GET /checkins.json
  def index
    @checkins = Checkin.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @checkins }
    end
  end

  # GET /checkins/1
  # GET /checkins/1.json
  def show
    @checkin = Checkin.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @checkin }
    end
  end

  # GET /checkins/new
  # GET /checkins/new.json
  def new
    @checkin = Checkin.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @checkin }
    end
  end

  # GET /checkins/1/edit
  def edit
    @checkin = Checkin.find(params[:id])
  end

  # POST /checkins
  # POST /checkins.json
  def create
    @checkin = Checkin.new(params[:checkin])

    respond_to do |format|
      if @checkin.save
        format.html { redirect_to :root, :notice => 'Checkin was successfully created.' }
        format.json { render :json => @checkin, :status => :created,:location => @checkin }
      else
        format.html { render :action => "new" }
        format.json { render :json => @checkin.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /checkins/1
  # PUT /checkins/1.json
  def update
    @checkin = Checkin.find(params[:id])

    respond_to do |format|
      if @checkin.update_attributes(params[:checkin])
        format.html { redirect_to @checkin, :notice => 'Checkin was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
      end
    end
  end

  def checkout
    @checkin = Checkin.find(params[:id])

    respond_to do |format|
      if @checkin.update_attributes(:checked_out_at => Time.now)
        format.html { redirect_to :back, :notice => 'Checkin was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
      end
    end
  end

  # DELETE /checkins/1
  # DELETE /checkins/1.json
  def destroy
    @checkin = Checkin.find(params[:id])
    @checkin.destroy

    respond_to do |format|
      format.html { redirect_to checkins_url }
      format.json { head :ok }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @checkins = Checkin.where(:checked_out_at => nil)
    @checkin = Checkin.new
    respond_to do |format|
      format.html
      format.json { render :json => @checkins }
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/checkins_helper.rb
module CheckinsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/checkins/_form.html.erb
<%= form_for(@checkin) do |f| %>
  <% if @checkin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@checkin.errors.count, "error") %> prohibited this checkin from being saved:</h2>

      <ul>
      <% @checkin.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :status %><br />
    <%= f.text_field :status %>
  </div>
  <div class="actions">
    <%= f.submit :value => "Check-in!", :redirect_to => root_path%>
  </div>
<% end %>

app/views/checkins/edit.html.erb
<h1>Editing checkin</h1>

<%= render 'form' %>

<%= link_to 'Show', @checkin %> |
<%= link_to 'Back', checkins_path %>

app/views/checkins/index.html.erb
<h1>Listing checkins</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Status</th>
    <th>Checked out at</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @checkins.each do |checkin| %>
  <tr>
    <td><%= checkin.name %></td>
    <td><%= checkin.email %></td>
    <td><%= checkin.status %></td>
    <td><%= checkin.checked_out_at %></td>
    <td><%= link_to 'Show', checkin %></td>
    <td><%= link_to 'Edit', edit_checkin_path(checkin) %></td>
    <td><%= link_to 'Destroy', checkin, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Checkin', new_checkin_path %>

app/views/checkins/new.html.erb
<h1>New checkin</h1>

<%= render 'form' %>

<%= link_to 'Back', root_path %>

app/views/checkins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @checkin.name %>
</p>

<p>
  <b>Email:</b>
  <%= @checkin.email %>
</p>

<p>
  <b>Status:</b>
  <%= @checkin.status %>
</p>

<p>
  <b>Checked in at:</b>
  <%= @checkin.created_at %>
</p>

<p>
  <b>Checked out at:</b>
  <%= @checkin.checked_out_at %>
</p>

<%= link_to 'Edit', edit_checkin_path(@checkin) %> |
<%= link_to 'Back', checkins_path %>

app/views/home/_form.html.erb
<div id="new-checkin">
<%= form_for(@checkin) do |f| %>
  <% if @checkin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@checkin.errors.count, "error") %> prohibited this checkin from being saved:</h2>

      <ul>
      <% @checkin.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field" id="name">
    <%= f.text_field :name, 
      :value => "What's your name?"%>
  </div>
  <div class="field" id="email">
    <%= f.text_field :email,
     :value => "What's your email?" %>
  </div>
  <div class="field" id="status">
    <%= f.text_field :status,
      :value => "What are you working on?" %>
  </div>
  <div class="actions">
    <%= f.submit :value=> "Check-in!" %>
  </div>
<% end %>
</div>

app/views/home/index.html.erb
<%= render 'form' %>
<div id="checked_in">
<h2><%= @checkins.length %> people currently checked in: </h2>
<table>
  <tr>
    <th>Name</th>
    <th>Working On</th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
 
<% @checkins.each do |checkin| %>
  <tr>
    <td class="checkin_name"><%= checkin.name %></td>
    <td class="checkin_status"><%= checkin.status %></td>
    <td class="checkout_link"><%= link_to 'check-out', checkin_path(checkin)+ '/checkout' %></td>
  </tr>
<% end %>
</table>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SviHackathon</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div id="wrapper">
    <div id="header">
      <h1>Who's at the SVI Summer Hackspace?</h1>
    </div>
    
    <div id="content">
      <%= yield %>
    </div>

    <div id="footer">

    </div>

</body>
</html>